const PDFDocument = require('pdfkit');

const NAVY = '#0B1F3A';
const GOLD = '#C7A24A';
const INK = '#1A1A1A';

/**
 * Renders a landscape Certificate of Recognition for students who
 * completed 6 or more categories across the Friday press-conference
 * sessions. DepEd-aligned layout: Division/School header block with a
 * logo placeholder, formal certifying paragraph, and two signature
 * lines (Adviser, School Principal / Head Teacher).
 */
function renderCertificatePdf({ student, categoriesCompleted, schoolName, divisionName, dateRange }, res) {
  const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: 40 });
  doc.pipe(res);

  const { width, height } = doc.page;

  // Decorative border (newspaper masthead feel: heavy double rule)
  doc.rect(20, 20, width - 40, height - 40).lineWidth(3).stroke(NAVY);
  doc.rect(30, 30, width - 60, height - 60).lineWidth(1).stroke(GOLD);

  // DepEd-style header block
  doc.circle(width / 2 - 220, 75, 26).lineWidth(1.2).stroke(NAVY);
  doc.fontSize(7).fillColor(NAVY).font('Helvetica-Bold')
    .text('DepEd\nSEAL', width / 2 - 246, 68, { width: 52, align: 'center' });

  doc.fontSize(11).fillColor(INK).font('Helvetica')
    .text('Republic of the Philippines', 0, 55, { align: 'center' });
  doc.fontSize(11).fillColor(INK).font('Helvetica')
    .text('DEPARTMENT OF EDUCATION', 0, 68, { align: 'center' });
  doc.fontSize(10).fillColor(INK).font('Helvetica-Oblique')
    .text(divisionName || 'Schools Division Office', 0, 82, { align: 'center' });
  doc.fontSize(13).fillColor(NAVY).font('Helvetica-Bold')
    .text((schoolName || 'YOUR SCHOOL NAME').toUpperCase(), 0, 98, { align: 'center' });

  // Title
  doc.moveDown(2);
  doc.fontSize(30).fillColor(NAVY).font('Times-Bold')
    .text('CERTIFICATE OF RECOGNITION', 0, 140, { align: 'center' });
  doc.fontSize(12).fillColor(GOLD).font('Helvetica-Oblique')
    .text('School Press Conference — Journalism Category Completion Awardee', 0, 178, { align: 'center' });

  // Body
  doc.fontSize(12).fillColor(INK).font('Helvetica')
    .text('This certificate is proudly presented to', 0, 215, { align: 'center' });

  doc.fontSize(24).fillColor(NAVY).font('Times-Bold')
    .text(student.full_name, 0, 240, { align: 'center' });

  doc.fontSize(10).fillColor(INK).font('Helvetica')
    .text(`Grade ${student.grade} - ${student.section}`, 0, 272, { align: 'center' });

  doc.fontSize(12).fillColor(INK).font('Helvetica')
    .text(
      `for successfully completing ${categoriesCompleted} journalism categories ` +
      `during the Friday School Press Conference sessions` +
      (dateRange ? ` held ${dateRange}` : '') +
      `, demonstrating dedication, versatility, and excellence in campus journalism.`,
      100, 300, { align: 'center', width: width - 200 }
    );

  // Signatures
  const sigY = height - 100;
  doc.moveTo(width / 2 - 220, sigY).lineTo(width / 2 - 60, sigY).lineWidth(0.75).stroke(INK);
  doc.fontSize(10).fillColor(INK).font('Helvetica-Bold')
    .text('Journalism Adviser', width / 2 - 220, sigY + 5, { width: 160, align: 'center' });

  doc.moveTo(width / 2 + 60, sigY).lineTo(width / 2 + 220, sigY).lineWidth(0.75).stroke(INK);
  doc.fontSize(10).fillColor(INK).font('Helvetica-Bold')
    .text('School Principal / Head Teacher', width / 2 + 60, sigY + 5, { width: 160, align: 'center' });

  doc.fontSize(8).fillColor(GOLD).font('Helvetica-Oblique')
    .text('Generated by the QR Code Attendance Management System', 0, height - 40, { align: 'center' });

  doc.end();
}

module.exports = { renderCertificatePdf };
